services:

  direct:
    image: __OSS_SIM_IMAGE__
    volumes:
      - ./src/:/src/:ro # Infrastructure location
    working_dir : /code/rundir
    env_file    : ./src/.env
    command     : pytest -o cache_dir=/code/rundir/.cache /src/test_runner.py -v -s
